import 'package:flutter/material.dart';

import 'theme.dart';
import 'package:mediaplex/home/models/category_card_model.dart';

Map<String, IconData> categories = {
  'Live': Icons.connected_tv,
  'News': Icons.newspaper,
  'Movies': Icons.movie,
  'Music': Icons.music_note_outlined,
  'Auto': Icons.two_wheeler,
  'Business': Icons.business,
  'Comedy': Icons.theater_comedy,
  'Documentary': Icons.theaters,
  'Education': Icons.school,
  'Entertainment': Icons.movie_filter_sharp,
  'Family': Icons.family_restroom,
  'Fashion': Icons.style,
  'Food': Icons.dinner_dining,
  'General': Icons.abc,
  'Health': Icons.health_and_safety,
  'History': Icons.history_edu,
  'Hobby': Icons.games,
  'Kids': Icons.child_friendly,
  'Legislative': Icons.policy,
  'Lifestyle': Icons.monitor_heart_rounded,
  'Local': Icons.local_activity,
  'Religious': Icons.temple_buddhist,
  'Shops': Icons.shop,
  'Sports': Icons.sports,
  'Travel': Icons.travel_explore,
  'Weather': Icons.sunny,
  'XXX': Icons.eighteen_up_rating,
  'Other': Icons.outbond_sharp
};

List<CategoryCardModel> categoryCards = categories.keys.map((_) => CategoryCardModel(
  type: _,
  count: 0,
  data: categories[_]!,
  child: _ == 'Live'
  ? Row(children: [
    Container(
      padding: const EdgeInsets.symmetric(horizontal: 5),
      decoration: BoxDecoration(color: Colors.red, borderRadius: BorderRadius.circular(10)),
      child: Text('Live', style: MyTheme.appText())
    ),
    const SizedBox(width: 4),
    Text('TV', style: MyTheme.appText())
  ]) : Text(_, overflow: TextOverflow.ellipsis, style: MyTheme.appText())
)).toList();

List<String> countryIcons = [
  'ae',
  'af',
  'al',
  'am',
  'ao',
  'ar',
  'at',
  'au',
  'aw',
  'az',
  'ba',
  'bb',
  'bd',
  'be',
  'bf',
  'bg',
  'bh',
  'bn',
  'bo',
  'br',
  'by',
  'ca',
  'cd',
  'ch',
  'ci',
  'cl',
  'cm',
  'cn',
  'co',
  'cr',
  'cw',
  'cr',
  'cw',
  'cy',
  'cz',
  'de',
  'dk',
  'do',
  'dz',
  'ec',
  'ee',
  'eg',
  'eh',
  'es',
  'et',
  'fi',
  'fj',
  'fo',
  'fr',
  'ge',
  'gh',
  'gm',
  'gq',
  'gr',
  'gy',
  'hk',
  'hn',
  'hr',
  'hu',
  'id',
  'ie',
  'il',
  'in',
  'ir',
  'is',
  'it',
  'jm',
  'jo',
  'jp',
  'ke',
  'kg',
  'kh',
  'kn',
  'kp',
  'kr',
  'kw',
  'kz',
  'la',
  'lb',
  'li',
  'lk',
  'lt',
  'lu',
  'lv',
  'ly',
  'ma',
  'md',
  'me',
  'mm',
  'mn',
  'mo',
  'mx',
  'my',
  'mz',
  'ng',
  'ni',
  'no',
  'np',
  'om',
  'pa',
  'pe',
  'ph',
  'pk',
  'pl',
  'pr',
  'ps',
  'pt',
  'py',
  'qa',
  'ro',
  'ru',
  'rw',
  'ad',
  'sa',
  'sd',
  'se',
  'sg',
  'si',
  'sk',
  'sm',
  'sn',
  'so',
  'sv',
  'sy',
  'th',
  'tj',
  'tm',
  'tn',
  'tr',
  'tt',
  'tz',
  'ua',
  'ug',
  'us',
  'uy',
  've',
  'ye',
  'za'
];